# Generated by Django 4.2.30 on 2026-05-28 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='OwnerType',
            fields=[
                ('owner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'owner_type',
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('lot_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('lot_name', models.CharField(max_length=50)),
                ('data_type', models.IntegerField()),
                ('addr', models.CharField(max_length=300)),
                ('car_space', models.IntegerField()),
                ('pregnancy_space', models.IntegerField(blank=True, null=True)),
                ('handicap_space', models.IntegerField(blank=True, null=True)),
                ('service_time', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('charge', models.CharField(max_length=500)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('owner_type', models.ForeignKey(db_column='owner_type', default=8, on_delete=django.db.models.deletion.CASCADE, to='api.ownertype')),
            ],
            options={
                'db_table': 'parking_lot',
            },
        ),
        migrations.CreateModel(
            name='RoadSide',
            fields=[
                ('road_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('road_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('geometry_wkt', models.TextField(blank=True, null=True)),
                ('total_car', models.IntegerField()),
                ('total_pregnancy', models.IntegerField()),
                ('total_handicap', models.IntegerField()),
                ('charge', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='api.area')),
            ],
            options={
                'db_table': 'road_side',
            },
        ),
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('his_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(max_length=11)),
                ('source_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=11)),
                ('note', models.CharField(max_length=50)),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'update_history',
            },
        ),
        migrations.CreateModel(
            name='ParkingLotStatus',
            fields=[
                ('lot', models.OneToOneField(db_column='lot_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.parkinglot')),
                ('ava_car', models.IntegerField(blank=True, null=True)),
                ('ava_handicap', models.IntegerField(blank=True, null=True)),
                ('ava_pregnancy', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parking_lot_status',
            },
        ),
        migrations.CreateModel(
            name='RoadSideStatus',
            fields=[
                ('road', models.OneToOneField(db_column='road_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.roadside')),
                ('ava_car', models.IntegerField(blank=True, null=True)),
                ('ava_pregnancy', models.IntegerField(blank=True, null=True)),
                ('ava_handicap', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'road_side_status',
            },
        ),
        migrations.CreateModel(
            name='YellowLineTest',
            fields=[
                ('yl_id', models.AutoField(primary_key=True, serialize=False)),
                ('road_name', models.CharField(max_length=500)),
                ('geometry_wkt', models.TextField(blank=True, null=True)),
                ('control_time', models.TextField(blank=True, null=True)),
                ('holiday_time', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='api.area')),
            ],
            options={
                'db_table': 'yellow_line_test',
            },
        ),
        migrations.CreateModel(
            name='YellowLineReal',
            fields=[
                ('yl_id', models.AutoField(primary_key=True, serialize=False)),
                ('road_name', models.CharField(max_length=500)),
                ('direction', models.CharField(max_length=5)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('geometry_wkt', models.TextField(blank=True, null=True)),
                ('standard_period', models.IntegerField(default=0)),
                ('control_time', models.TextField(blank=True, null=True)),
                ('holiday_time', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='api.area')),
            ],
            options={
                'db_table': 'yellow_line_real',
            },
        ),
        migrations.CreateModel(
            name='ParkingRateRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_mask', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hourly_rate', models.IntegerField(blank=True, null=True)),
                ('per_time_rate', models.IntegerField(blank=True, null=True)),
                ('rate_text', models.CharField(blank=True, max_length=255, null=True)),
                ('lot', models.ForeignKey(db_column='lot_id', on_delete=django.db.models.deletion.CASCADE, to='api.parkinglot')),
            ],
            options={
                'db_table': 'parking_rate_rule',
            },
        ),
    ]
