# Generated by Django 4.2.30 on 2026-05-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=150)),
                ('action_type', models.CharField(max_length=20)),
                ('target_table', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_action_log',
            },
        ),
    ]
